name: Build Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'liberica'

    - name: Permission to gradle(bruh)
      run: sudo chmod +x gradlew
    
    - name: Setup ForgeGradle
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx8G setupDecompWorkspace
      
    - name: Build
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: raven
        path: ./build/libs/raven.jar
